# Deliverable 1. Retrieve Weather Data.
---
1. Create a folder called `Weather_Database` to save all the files related with this deliverable.

2. Save the `Weather_Database_starter_code.ipynb` starter code to the `Weather_Database` folder and rename it as `Weather_Database.ipynb`.

3. Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

4. Use the `citipy` module to get the nearest city for each latitude and longitude combination.

5. Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key; also, it's critical to avoid publishing your API key on your GitHub repository.

6. Retrieve the following information from the API call:

    * Latitude and longitude

    * Maximum temperature

    * Percent humidity

    * Percent cloudiness

    * Wind speed

    * Weather description (for example, clouds, fog, light rain, clear sky)

7. Add the weather data to a new DataFrame.

8. Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.
---

In [1]:
# Import initial libraries
import numpy as np
import pandas as pd
from citipy import citipy

## Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

In [2]:
# Create a set of random latitude and longitude combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)

# Use the zip function to create an iterator of tuples containing the latitude and longitude combinations
lat_lngs = zip(lats, lngs)

In [3]:
# Add the latitudes and longitudes to a list
coordinates = list(lat_lngs)

## Use the `citipy` module to get the nearest city for each latitude and longitude combination.

In [4]:
# Create an empty list for holding the cities
cities = []

# Use a for loop to identify nearest city for each latitude and longitude combination using the citipy module
for coordinate in coordinates:
    # Use the citipy module to identify the nearest city to the current coordinate
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

193

## Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key.

In [5]:
# Import the requests library
import requests

# Import the time library
import time

# Import the datetime module from the datetime library
from datetime import datetime

# Import the OpenWeatherMap's API key
from config import weather_api_key

In [6]:
# Assemble the OpenWeatherMap's API call
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

## Retrieve the following information from the API call.

- The latitude and longitude
- The Max temperature
- The % humidity
- The % cloudiness
- The Wind speed
- The Weather description, i.e., cloudy, fog, light rain, clear sky, etc.

In [12]:
# Create an empty list to hold weather data for each city
city_data = []

# Print a message to indicate that the data retrieval starts
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters and set them to 1
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data for each city
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create an endpoint URL for each city
    city_url = url + "&q=" + city.replace(" ","+")
    
    # Log the url, record, and set numbers
    print(f"Processing Record {record_count} of Set {set_count} | {city}")

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        city_weather = requests.get(city_url).json()
        
        # Parse out the latitude, longitude, max temp, humidity, cloudiness, wind, country, and weather description
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"] 
        city_description = city_weather["weather"][0]["description"]
            
        # Append the city information into the city_data list
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Current Description": city_description})
    
    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        #pass

# Indicate that the data retrieval is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | palu
Processing Record 2 of Set 1 | qaanaaq
Processing Record 3 of Set 1 | bethel
Processing Record 4 of Set 1 | iwaki
Processing Record 5 of Set 1 | norman wells
Processing Record 6 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 7 of Set 1 | opoczno
Processing Record 8 of Set 1 | salmas
Processing Record 9 of Set 1 | faya
Processing Record 10 of Set 1 | hermanus
Processing Record 11 of Set 1 | poum
Processing Record 12 of Set 1 | richards bay
Processing Record 13 of Set 1 | nyurba
Processing Record 14 of Set 1 | paracuru
Processing Record 15 of Set 1 | wagar
Processing Record 16 of Set 1 | kaduqli
Processing Record 17 of Set 1 | mar del plata
Processing Record 18 of Set 1 | yuanping
Processing Record 19 of Set 1 | port alfred
Processing Record 20 of Set 1 | cidreira
Processing Record 21 of Set 1 | ushuaia
Processing Record 22 of Set 1 | atuona
Processing Record 23 of Set 1 | rikitea
Processing Record 24 of Set 1 | arraial do cabo
Processing Record 25 of Set 1 | bluff
Processing Record 26 of Set 1 | rawson
Processing Record 27 of Set 1 | belushya guba
City not found. Skipping...
Processing Record 28 of Set 1 | new norfolk
Processing Record 29 of Set 1 | faanui
Processing Record 30 of Set 1 | rocha
Processing Record 31 of Set 1 | ngaoundere
Processing Record 32 of Set 1 | vaini
Processing Record 33 of Set 1 | hilo
Processing Record 34 of Set 1 | bengkulu
Processing Record 35 of Set 1 | castro
Processing Record 36 of Set 1 | bandarbeyla
Processing Record 37 of Set 1 | fort wellington
Processing Record 38 of Set 1 | punta arenas
Processing Record 39 of Set 1 | hasaki
Processing Record 40 of Set 1 | clyde river
Processing Record 41 of Set 1 | attawapiskat
City not found. Skipping...
Processing Record 42 of Set 1 | busselton
Processing Record 43 of Set 1 | ishigaki
Processing Record 44 of Set 1 | tura
Processing Record 45 of Set 1 | atengo
Processing Record 46 of Set 1 | morant bay
Processing Record 47 of Set 1 | kazalinsk
City not found. Skipping...
Processing Record 48 of Set 1 | albany
Processing Record 49 of Set 1 | hobart
Processing Record 50 of Set 1 | shenjiamen
Processing Record 1 of Set 2 | kahului
Processing Record 2 of Set 2 | barrow
Processing Record 3 of Set 2 | bela vista
Processing Record 4 of Set 2 | butaritari
Processing Record 5 of Set 2 | santiago del estero
Processing Record 6 of Set 2 | hay river
Processing Record 7 of Set 2 | sur
Processing Record 8 of Set 2 | torbay
Processing Record 9 of Set 2 | aklavik
Processing Record 10 of Set 2 | tutoia
Processing Record 11 of Set 2 | raudeberg
Processing Record 12 of Set 2 | tuktoyaktuk
Processing Record 13 of Set 2 | kalabo
Processing Record 14 of Set 2 | paka
Processing Record 15 of Set 2 | awbari
Processing Record 16 of Set 2 | mataura
Processing Record 17 of Set 2 | narsaq
Processing Record 18 of Set 2 | camana
Processing Record 19 of Set 2 | kununurra
Processing Record 20 of Set 2 | polson
Processing Record 21 of Set 2 | mago
Processing Record 22 of Set 2 | tottori
Processing Record 23 of Set 2 | yuzhno-yeniseyskiy
City not found. Skipping...
Processing Record 24 of Set 2 | codrington
Processing Record 25 of Set 2 | mandera
Processing Record 26 of Set 2 | hambantota
Processing Record 27 of Set 2 | klaksvik
Processing Record 28 of Set 2 | yellowknife
Processing Record 29 of Set 2 | caravelas
Processing Record 30 of Set 2 | henties bay
Processing Record 31 of Set 2 | surt
Processing Record 32 of Set 2 | amderma
City not found. Skipping...
Processing Record 33 of Set 2 | atasu
Processing Record 34 of Set 2 | westport
Processing Record 35 of Set 2 | cape town
Processing Record 36 of Set 2 | ballina
Processing Record 37 of Set 2 | ishim
Processing Record 38 of Set 2 | yorkton
Processing Record 39 of Set 2 | saint-philippe
Processing Record 40 of Set 2 | halifax
Processing Record 41 of Set 2 | chokurdakh
Processing Record 42 of Set 2 | palmer
Processing Record 43 of Set 2 | san cristobal
Processing Record 44 of Set 2 | oktyabrskiy
Processing Record 45 of Set 2 | suntar
Processing Record 46 of Set 2 | djibo
Processing Record 47 of Set 2 | namatanai
Processing Record 48 of Set 2 | tanda
Processing Record 49 of Set 2 | khatanga
Processing Record 50 of Set 2 | gari
Processing Record 1 of Set 3 | evensk
Processing Record 2 of Set 3 | paamiut
Processing Record 3 of Set 3 | taolanaro
City not found. Skipping...
Processing Record 4 of Set 3 | baykit
Processing Record 5 of Set 3 | la romana
Processing Record 6 of Set 3 | lolua
City not found. Skipping...
Processing Record 7 of Set 3 | lingao
Processing Record 8 of Set 3 | lagoa
Processing Record 9 of Set 3 | nikolskoye
Processing Record 10 of Set 3 | daru
Processing Record 11 of Set 3 | washington
Processing Record 12 of Set 3 | mwingi
Processing Record 13 of Set 3 | freeport
Processing Record 14 of Set 3 | saint george
Processing Record 15 of Set 3 | hithadhoo
Processing Record 16 of Set 3 | milkovo
Processing Record 17 of Set 3 | cayenne
Processing Record 18 of Set 3 | jamestown
Processing Record 19 of Set 3 | bosaso
Processing Record 20 of Set 3 | avarua
Processing Record 21 of Set 3 | mehamn
Processing Record 22 of Set 3 | saint-joseph
Processing Record 23 of Set 3 | xining
Processing Record 24 of Set 3 | umm durman
City not found. Skipping...
Processing Record 25 of Set 3 | bredasdorp
Processing Record 26 of Set 3 | sao joao da barra
Processing Record 27 of Set 3 | upernavik
Processing Record 28 of Set 3 | shiyan
Processing Record 29 of Set 3 | port lincoln
Processing Record 30 of Set 3 | morondava
Processing Record 31 of Set 3 | nome
Processing Record 32 of Set 3 | jatai
Processing Record 33 of Set 3 | itarema
Processing Record 34 of Set 3 | jalu
Processing Record 35 of Set 3 | bolshevik
Processing Record 36 of Set 3 | vao
Processing Record 37 of Set 3 | luangwa
Processing Record 38 of Set 3 | yining
Processing Record 39 of Set 3 | severo-kurilsk
Processing Record 40 of Set 3 | coquimbo
Processing Record 41 of Set 3 | brownsville
Processing Record 42 of Set 3 | ilulissat
Processing Record 43 of Set 3 | portsmouth
Processing Record 44 of Set 3 | srandakan
Processing Record 45 of Set 3 | barra do garcas
Processing Record 46 of Set 3 | te anau
Processing Record 47 of Set 3 | zemio
Processing Record 48 of Set 3 | kapaa
Processing Record 49 of Set 3 | somerset east
Processing Record 50 of Set 3 | rancho palos verdes
Processing Record 1 of Set 4 | havre-saint-pierre
Processing Record 2 of Set 4 | dikson
Processing Record 3 of Set 4 | cornwall
Processing Record 4 of Set 4 | boende
Processing Record 5 of Set 4 | jamkhed
Processing Record 6 of Set 4 | kaitangata
Processing Record 7 of Set 4 | koping
Processing Record 8 of Set 4 | porto novo
Processing Record 9 of Set 4 | fortuna
Processing Record 10 of Set 4 | georgetown
Processing Record 11 of Set 4 | pangnirtung
Processing Record 12 of Set 4 | pampas
Processing Record 13 of Set 4 | mys shmidta
City not found. Skipping...
Processing Record 14 of Set 4 | corn island
Processing Record 15 of Set 4 | hetauda
Processing Record 16 of Set 4 | belaya gora
Processing Record 17 of Set 4 | seoul
Processing Record 18 of Set 4 | provideniya
Processing Record 19 of Set 4 | rubano
Processing Record 20 of Set 4 | cherskiy
Processing Record 21 of Set 4 | havoysund
Processing Record 22 of Set 4 | sorvag
City not found. Skipping...
Processing Record 23 of Set 4 | iqaluit
Processing Record 24 of Set 4 | margate
Processing Record 25 of Set 4 | saskylakh
Processing Record 26 of Set 4 | mahebourg
Processing Record 27 of Set 4 | mayumba
Processing Record 28 of Set 4 | saldanha
Processing Record 29 of Set 4 | fort nelson
Processing Record 30 of Set 4 | ambodifototra
City not found. Skipping...
Processing Record 31 of Set 4 | bangassou
Processing Record 32 of Set 4 | lesnica
Processing Record 33 of Set 4 | hervey bay
Processing Record 34 of Set 4 | khonuu
City not found. Skipping...
Processing Record 35 of Set 4 | sistranda
Processing Record 36 of Set 4 | grand river south east
City not found. Skipping...
Processing Record 37 of Set 4 | trincomalee
Processing Record 38 of Set 4 | cap malheureux
Processing Record 39 of Set 4 | aykhal

Processing Record 40 of Set 4 | kavieng
Processing Record 41 of Set 4 | sentyabrskiy
City not found. Skipping...
Processing Record 42 of Set 4 | borogontsy
Processing Record 43 of Set 4 | sept-iles
-----------------------------
Data Retrieval Complete
-----------------------------

In [13]:
# Print the length of the city_data list to verify how many cities you have
len(city_data)

178

## Add the weather data to a new DataFrame.

In [14]:
# Use the city_data list to create a new pandas DataFrame.
city_data_df = pd.DataFrame(city_data)

In [15]:
# Display sample data
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Palu,ID,-0.8917,119.8707,90.34,51,93,4.68,overcast clouds
1,Qaanaaq,GL,77.4840,-69.3632,1.11,61,100,5.21,overcast clouds
2,Bethel,US,41.3712,-73.4140,44.96,73,100,3.44,overcast clouds
3,Iwaki,JP,37.0500,140.8833,43.02,48,13,4.00,few clouds
4,Norman Wells,CA,65.2820,-126.8329,-2.13,94,100,6.64,overcast clouds
5,Opoczno,PL,51.3757,20.2783,42.91,86,82,8.37,broken clouds
6,Salmas,IR,38.1973,44.7653,25.39,58,0,1.81,clear sky
7,Faya,SA,18.3851,42.4509,50.52,76,88,2.06,overcast clouds
8,Hermanus,ZA,-34.4187,19.2345,69.80,82,9,15.23,clear sky
9,Poum,NC,-20.2333,164.0167,79.32,71,12,10.58,few clouds

In [16]:
# Display the DataFrame's column names using the columns Pandas function
city_data_df.columns

Index(['City', 'Country', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness',
       'Wind Speed', 'Current Description'],
      dtype='object')

In [17]:
# Create a list to reorder the column names as follows:
# "City", "Country", "Lat", "Lng", "Max Temp", "Humidity",  "Cloudiness", "Wind Speed",  "Current Description"
new_column_order = ['City', 'Country', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness', 'Wind Speed', 'Current Description']

# Recreate the DataFrame by using the new column order
city_data_df = city_data_df[new_column_order]

# Display sample data
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Palu,ID,-0.8917,119.8707,90.34,51,93,4.68,overcast clouds
1,Qaanaaq,GL,77.4840,-69.3632,1.11,61,100,5.21,overcast clouds
2,Bethel,US,41.3712,-73.4140,44.96,73,100,3.44,overcast clouds
3,Iwaki,JP,37.0500,140.8833,43.02,48,13,4.00,few clouds
4,Norman Wells,CA,65.2820,-126.8329,-2.13,94,100,6.64,overcast clouds
5,Opoczno,PL,51.3757,20.2783,42.91,86,82,8.37,broken clouds
6,Salmas,IR,38.1973,44.7653,25.39,58,0,1.81,clear sky
7,Faya,SA,18.3851,42.4509,50.52,76,88,2.06,overcast clouds
8,Hermanus,ZA,-34.4187,19.2345,69.80,82,9,15.23,clear sky
9,Poum,NC,-20.2333,164.0167,79.32,71,12,10.58,few clouds

In [18]:
# Display the data types of each column by using the dtypes Pandas function
city_data_df.dtypes

City                    object
Country                 object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

## Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.

In [21]:
# Set the output file name
output_data_file = './WeatherPy_Database.csv'

# Export the city_data DataFrame into a CSV file
city_data_df.to_csv(output_data_file, index_label='City_ID')